security:
    providers:
        cookie:
            id: nerdery_xbox.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: nerdery_xbox.cookie_authenticator
